CREATE TABLE tenants (
  id VARCHAR(36) PRIMARY KEY,
  tenant_code VARCHAR(50) NOT NULL UNIQUE,
  tenant_name VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL,
  deleted_at TIMESTAMP NULL
);

CREATE TABLE tenant_users (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  display_name VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(2000) NULL,
  status VARCHAR(20) NOT NULL,
  last_login_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL,
  CONSTRAINT fk_test_user_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE tenant_user_credentials (
  tenant_user_id VARCHAR(36) PRIMARY KEY,
  password_hash VARCHAR(255) NOT NULL,
  password_algorithm VARCHAR(30) NOT NULL,
  must_change_password BOOLEAN NOT NULL,
  password_changed_at TIMESTAMP NULL,
  password_expires_at TIMESTAMP NULL,
  failed_login_count SMALLINT NOT NULL,
  locked_until TIMESTAMP NULL,
  reset_token_hash VARCHAR(64) NULL,
  reset_token_expires_at TIMESTAMP NULL,
  credential_version INT NOT NULL,
  CONSTRAINT fk_test_credential_user FOREIGN KEY (tenant_user_id) REFERENCES tenant_users(id)
);

CREATE TABLE tenant_password_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_user_id VARCHAR(36) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  password_algorithm VARCHAR(30) NOT NULL,
  changed_at TIMESTAMP NOT NULL,
  changed_by_type VARCHAR(20) NOT NULL,
  CONSTRAINT fk_test_password_history_user
    FOREIGN KEY (tenant_user_id) REFERENCES tenant_users(id)
);

CREATE TABLE roles (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NULL,
  tenant_scope_key VARCHAR(36) NOT NULL,
  role_code VARCHAR(50) NOT NULL
);

CREATE TABLE permissions (
  id VARCHAR(36) PRIMARY KEY,
  permission_code VARCHAR(100) NOT NULL
);

CREATE TABLE role_permissions (
  role_id VARCHAR(36) NOT NULL,
  permission_id VARCHAR(36) NOT NULL,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE tenant_user_roles (
  tenant_user_id VARCHAR(36) NOT NULL,
  tenant_id VARCHAR(36) NOT NULL,
  role_id VARCHAR(36) NOT NULL,
  role_scope_key VARCHAR(36) NOT NULL,
  PRIMARY KEY (tenant_user_id, role_id)
);

CREATE TABLE login_sessions (
  id VARCHAR(36) PRIMARY KEY,
  actor_type VARCHAR(20) NOT NULL,
  tenant_user_id VARCHAR(36) NOT NULL,
  session_token_hash VARCHAR(64) NOT NULL UNIQUE,
  auth_stage VARCHAR(30) NOT NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(500) NULL,
  issued_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP NULL,
  CONSTRAINT fk_test_session_user FOREIGN KEY (tenant_user_id) REFERENCES tenant_users(id)
);

CREATE TABLE security_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(36) NULL,
  actor_type VARCHAR(20) NOT NULL,
  actor_id VARCHAR(36) NULL,
  action_code VARCHAR(100) NOT NULL,
  target_type VARCHAR(50) NULL,
  target_id VARCHAR(200) NULL,
  result VARCHAR(20) NOT NULL,
  ip_address VARCHAR(45) NULL,
  metadata_json JSON NOT NULL,
  occurred_at TIMESTAMP NOT NULL,
  CONSTRAINT ck_security_audit_result
    CHECK (result IN ('SUCCEEDED', 'FAILED', 'DENIED'))
);

CREATE TABLE marketplaces (
  id VARCHAR(36) PRIMARY KEY,
  marketplace_code VARCHAR(30) NOT NULL UNIQUE,
  marketplace_name VARCHAR(100) NOT NULL,
  mock_base_url VARCHAR(500) NULL,
  is_active BOOLEAN NOT NULL
);

CREATE TABLE marketplace_accounts (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  marketplace_id VARCHAR(36) NOT NULL,
  external_account_id VARCHAR(200) NOT NULL,
  shop_cipher VARCHAR(255) NULL,
  external_shop_name VARCHAR(255) NOT NULL,
  site_id VARCHAR(10) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  timezone_name VARCHAR(64) NOT NULL,
  connection_status VARCHAR(20) NOT NULL,
  authorized_at TIMESTAMP NULL,
  expires_at TIMESTAMP NULL,
  last_verified_at TIMESTAMP NULL,
  settings_json JSON NOT NULL,
  created_by_user_id VARCHAR(36) NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP NULL,
  CONSTRAINT fk_test_marketplace_account_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_test_marketplace_account_marketplace
    FOREIGN KEY (marketplace_id) REFERENCES marketplaces(id),
  CONSTRAINT uq_test_marketplace_account_scope
    UNIQUE (tenant_id, marketplace_id, external_account_id)
);

CREATE TABLE marketplace_credentials (
  id VARCHAR(36) PRIMARY KEY,
  marketplace_account_id VARCHAR(36) NOT NULL UNIQUE,
  app_key VARCHAR(150) NULL,
  access_token_encrypted MEDIUMTEXT NOT NULL,
  refresh_token_encrypted MEDIUMTEXT NULL,
  scopes_json JSON NOT NULL,
  encryption_key_version VARCHAR(30) NOT NULL,
  access_token_expires_at TIMESTAMP NULL,
  refresh_token_expires_at TIMESTAMP NULL,
  last_refreshed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_test_marketplace_credential_account
    FOREIGN KEY (marketplace_account_id) REFERENCES marketplace_accounts(id)
);

CREATE TABLE marketplace_connection_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marketplace_account_id VARCHAR(36) NOT NULL,
  from_status VARCHAR(20) NULL,
  to_status VARCHAR(20) NOT NULL,
  reason_code VARCHAR(100) NULL,
  details_json JSON NOT NULL,
  changed_by_user_id VARCHAR(36) NULL,
  occurred_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_test_marketplace_history_account
    FOREIGN KEY (marketplace_account_id) REFERENCES marketplace_accounts(id)
);

CREATE TABLE oauth_authorization_sessions (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL,
  tenant_user_id VARCHAR(36) NOT NULL,
  marketplace_id VARCHAR(36) NOT NULL,
  state_hash VARCHAR(64) NOT NULL UNIQUE,
  requested_scopes_json JSON NOT NULL,
  return_url VARCHAR(500) NULL,
  status VARCHAR(20) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  consumed_at TIMESTAMP NULL,
  failure_code VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_test_oauth_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_test_oauth_user
    FOREIGN KEY (tenant_user_id) REFERENCES tenant_users(id),
  CONSTRAINT fk_test_oauth_marketplace
    FOREIGN KEY (marketplace_id) REFERENCES marketplaces(id)
);
